from turtle import *
def square(frw):
    speed(0)
    for i in range(4):
        forward(frw)
        left(90)
def triangle(frw):
    speed(0)
    for i in range(3):
        forward(frw)
        left(120)
def star(coloru, frw):
    speed(0)
    color(coloru)
    begin_fill()
    for i in range(18):
        forward(frw)
        left(100)
    end_fill()
def penupdown(go, to):
    speed(0)
    penup()
    goto(go, to)
    pendown()
def med(l, i):
    speed(0)
    penupdown(l, i)
    color('lavender')
    begin_fill()
    square(200)
    end_fill()
    penupdown(l + 0, i + 0)
    color('gray')
    begin_fill()
    rectangle(50, 150)
    end_fill()
    color('red')
    penupdown(l-20, i +200)
    begin_fill()
    rectangle(100, 50)
    end_fill()
    penupdown(l +0, i +180)
    begin_fill()
    rectangle(50, 100)
    end_fill()
def rectangle(lenght, f1rw):
    speed(0)
    for i in range(2):
        forward(lenght)
        left(90)
        forward(f1rw)
        left(90)
def tree(kor, leght):
    speed(0)
    color('green')
    pens1ze = 10
    pensize(10)
    for i in range(26):
        forward(pens1ze)
        left(90)
        pens1ze+= 5
    color('brown')
    pensize(20)
    penup()
    goto(kor, leght)
    pendown()
    left(90)
    forward(200)
    left(90)
def home():
    speed(0)
    begin_fill()
    color('black','brown')
    penupdown(-50, 0)
    square(200)
    end_fill()
    penupdown(-14, 0)
    begin_fill()
    color('black','orange')
    rectangle(30, 50)
    end_fill()
    penupdown(50, 60)
    begin_fill()
    color('black','lightblue')
    square(30)
    end_fill()
    penupdown(-30, 80)
    begin_fill()
    color('black','lightblue')
    square(30)
    end_fill()
    color('black','orange')
    penupdown(-60, 185)
    begin_fill()
    triangle(220)
    end_fill()
def fence_link():
    speed(0)
    pensize(2)
    color("black","orange")
    begin_fill()
    left(90)
    forward(100)
    right(30)
    forward(42)
    right(120)
    forward(42)
    right(30)
    forward(100)
    right(90)
    forward(42)
    left(180)
    end_fill()
def fence(go, to):
    penupdown(go, to)
    for i in range(6):
        fence_link()
        penup()
        go += 42
        goto(go, to)
        pendown()
